### ISSUE TITLE
App Crash : Showing client side error in docs

### ISSUE THREAD

**Issue by govindpvenu** [codse/animata#207] opened 2024-09-26 13:30 UTC
When clicking button overiew under buttons section the app crashes and showing this message:
Application error: a client-side exception has occurred (see the browser console for more information).

Check this page:
https://animata.design/docs/button

Console show this error
![image](https://github.com/user-attachments/assets/996c6333-54f5-4aa5-9766-07ed73b30c1c)

**Comment by hari** [comment] 2024-09-29 16:37
@govindpvenu Could you try now?

Closing this as duplicate of #192

**Closed by hari** 2024-09-29 16:37 UTC
